Feat/no staking test case
valory-xyz/quickstart pull request #3
Opened 2024-12-18 16:29 UTC by Mohsinsiddi

Added  Test Script for No Staking Option

2024-12-18 19:12 UTC, OjusWiZard requested changes
Beautifully done @Mohsinsiddi! I've asked somethings. Also, let's organise the dev/testing dependencies with the current method (poetry) only. It will keep things clean and modular.

2024-12-18 19:12 UTC, OjusWiZard commented on tests/test_run_service.py
> +
this should fail the test, right?
```suggestion
            raise Exception(f"Test failed with exit status {child.exitstatus}")
            
```

2024-12-18 19:12 UTC, OjusWiZard commented on tests/test_run_service.py
> +        logger.error(f"Test failed with error: {str(e)}")
this also should fail the test
```suggestion
        raise Exception(f"Test failed with error: {str(e)}")
```

2024-12-19 16:33 UTC, Mohsinsiddi commented on tests/test_run_service.py
> +        os.chmod(script_path, 0o755)
removed it

2024-12-19 16:33 UTC, Mohsinsiddi commented on tests/test_run_service.py
> +                break
added raise

2024-12-20 08:13 UTC, closed without merging